# My First Github Action script

name: My-Gitub-Actions
env:
  APPLICATION_NAME    : "MyApp"
  DEPLOY_PACKAGE_NAME : "App-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello message
      run : echo "Hello world from Test Job"
      
    - name: Execute few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}" 
        
    - name: List current folder
      run : ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1  
  
    - name: List current folder
      run : ls -la
      

  my_prod:
    runs-on: ubuntu-latest
    needs: [my_test]
    env:
      VAR1: "This is Job 1"
      VAR2: "This is Job 2"
    
    steps:
    - name: Print Hello message
      run : echo "Hello world from Prod Job"
    
    - name: Print env vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Local Environment Variable"
      
    - name: Print Deployment Package
      run : echo "Deploy Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
    - name: Let's test some packages if they are there 1
      run : aws --version
      
    - name: Let's test some packages if they are there 2
      run : zip --version 











