# My First Github Action script

name: My-Gitub-Actions

on:
  push:
    branches:
      - master

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello message
      run : echo "Hello world from Test Job"

  my_prod:
    runs-on: ubuntu-latest
    needs: [my_test]
    
    steps:
    - name: Print Hello message
      run : echo "Hello world from Prod Job"













