# My First Github Action script

name: My-Gitub-Actions
env:
  APPLICATION_NAME    : "MyApp"
  DEPLOY_PACKAGE_NAME : "App-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello message
      run : echo "Hello world from Test Job"
      
    - name: Execute few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}" 

  my_prod:
    runs-on: ubuntu-latest
    needs: [my_test]
    
    steps:
    - name: Print Hello message
      run : echo "Hello world from Prod Job"
      
    - name: Print Deployment Package
      run : echo "Deploy Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"











